const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){const nodes={};const c=vm.createContext({URLSearchParams,document:{addEventListener(){},querySelectorAll(){return []}}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/static/js/portfolio.js'),'utf8'),c);c.esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');c.portalDateTime=String;c.$=s=>nodes[s]||(nodes[s]={});c.PORTAL={epoch:1};c.LIVE_REQUEST={text:'Unsent work',busy:false};c.INTAKE={busy:false};c.PORTAL_PDF={busy:false};c.TRAIN={};c.state={};c.render=c.focusPageStart=()=>{};c.portalError=e=>e.message;return {c,nodes}}
const handoff={id:7,item_id:2,kind:'REQUEST',available:true,context:{prefill:'Skill context',title:'Planning'}};
test('handoff GET only prepares existing request and preserves draft',async()=>{const {c}=setup(),calls=[];c.apiRequest=async(url,opts)=>{calls.push({url,opts});return handoff};await c.portfolioContinue(7);assert.equal(calls.length,1);assert.equal(calls[0].opts,undefined);assert.match(c.LIVE_REQUEST.text,/Unsent work/);assert.match(c.LIVE_REQUEST.text,/Skill context/);assert.equal(c.PFL.source.id,7);assert.equal(c.state.currentPage,'submitter-request');assert.equal(c.LIVE_REQUEST.submissionKey,null)});
test('full draft is never truncated and reopening same handoff does not duplicate context',async()=>{const {c}=setup();c.apiRequest=async()=>handoff;c.LIVE_REQUEST.text='x'.repeat(5000);await c.portfolioContinue(7);assert.equal(c.LIVE_REQUEST.text.length,5000);await c.portfolioContinue(7);assert.equal(c.LIVE_REQUEST.text,'x'.repeat(5000))});
test('dirty session draft prevents replacement and does not change source',async()=>{const {c,nodes}=setup();c.TRAIN.draft={dirty:true,title:'unsent'};c.PFL.source={id:99};c.apiRequest=async()=>({...handoff,kind:'SESSION',context:{course_version_id:3}});await c.portfolioContinue(7);assert.equal(c.TRAIN.draft.title,'unsent');assert.equal(c.PFL.source.id,99);assert.match(nodes['#portfolioError'].innerHTML,/taslağınız/)});
test('session shortcut prepares existing form without creating session',async()=>{const {c}=setup();let calls=0;c.apiRequest=async()=>{calls++;return {...handoff,kind:'SESSION',context:{course_version_id:3}}};await c.portfolioContinue(7);assert.equal(calls,1);assert.equal(c.TRAIN.courseVersionId,3);assert.equal(c.TRAIN.portfolioHandoffId,7);assert.equal(c.state.currentPage,'portal-training-create')});
test('enrichment source attaches only to the selected request',()=>{const {c}=setup();c.PFL.source={id:8,kind:'DEVELOPMENT',context:{source_request_id:10}};assert.equal(c.portfolioSourceId('DEVELOPMENT',10),8);assert.equal(c.portfolioSourceId('DEVELOPMENT',11),null);assert.equal(c.portfolioSourceId('REQUEST'),null)});
test('account reset removes all private drafts and handoff context',()=>{const {c}=setup();c.PFL.source=handoff;c.PFL.drafts={1:{note:'private'}};c.resetPortfolio();assert.equal(c.PFL.source,null);assert.deepEqual(Object.keys(c.PFL.drafts),[])});
test('stale GET after account switch cannot populate another account draft',async()=>{const {c}=setup();let resolve;c.apiRequest=()=>new Promise(r=>resolve=r);const work=c.portfolioContinue(7);c.resetPortfolio();resolve(handoff);await work;assert.equal(c.PFL.source,null);assert.equal(c.LIVE_REQUEST.text,'Unsent work')});
test('hidden counts are distinct from zero and unsafe markup is escaped',()=>{const {c}=setup();assert.match(c.portfolioNumber(null),/Gizli/);assert.equal(c.portfolioNumber(0),'0');const h=c.portfolioSignals([{type:'CONTENT_GAP',explanation:'<img>',label:'<script>'}]);assert.ok(!h.includes('<script>'));assert.match(h,/&lt;script&gt;/)});
test('snapshot renders stored version and safe counts without recalculating',()=>{const {c}=setup();c.apiRequest=()=>{throw Error('No network in historic snapshot')};const html=c.portfolioSnapshot({generated_at:'2026-09-01',scope:'ORGANIZATION',planned_profiles:2,observed_needs:null,open_needs:null,resolved_needs:null,published_versions:0,repeated_needs:null,signals:[],catalog:[],training:{}});assert.match(html,/2026-09-01/);assert.match(html,/Gizli/)});
test('out of order filters cannot overwrite current portfolio results',async()=>{const {c,nodes}=setup(),pending=[];c.portalEmpty=()=>'';c.apiRequest=()=>new Promise(r=>pending.push(r));const data=n=>({items:[],total:n,summary:{},groups:[],signal_types:{},policy:{}});const a=c.loadPortfolio();c.PFL.filters.coverage='MISSING';const b=c.loadPortfolio();pending[1](data(22));await b;pending[0](data(11));await a;assert.match(nodes['#portfolioOverview'].innerHTML,/22 yetkinlik/);assert.ok(!nodes['#portfolioOverview'].innerHTML.includes('11 yetkinlik'))});
