const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){const c=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/static/js/positions.js'),'utf8'),c);c.esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');c.portalDateTime=String;return c}
function requirement(extra={}){return {id:9,skill_id:2,skill:'SQL',type_label:'Gerekli',state_label:'Kanıt bulunamadı',evidence_count:0,last_evidence_at:null,rationale:'İş gereksinimi',explanation:['Bu yetkinlik için sistemde henüz kanıt bulunmuyor.'],courses:[],can_request:true,...extra}}
test('no evidence has neutral language and no artificial level or score',()=>{const c=setup(),html=c.roleRequirementHTML(requirement());assert.match(html,/Kanıt bulunamadı/);assert.match(html,/Kayıt yok/);assert.ok(!html.includes('data-skill-mine'));assert.ok(!html.includes('%'));assert.ok(!html.includes('yetkin değil'));assert.match(html,/İçerik kapsamı bulunmuyor/)});
test('course suggestions and evidence links use only the supplied source identifiers',()=>{const c=setup(),html=c.roleRequirementHTML(requirement({evidence_count:1,state_label:'Gelişim kanıtı mevcut',courses:[{id:4,title:'<script>',version_number:2}],can_request:false}));assert.match(html,/data-pub-open="4"/);assert.match(html,/data-skill-mine="2"/);assert.ok(!html.includes('data-position-need'));assert.match(html,/&lt;script&gt;/)});
test('role shortcut preserves unsent text and makes no network request',()=>{const c=setup();let calls=0,renders=0;c.apiRequest=()=>calls++;c.render=()=>renders++;c.focusPageStart=()=>{};c.state={};c.INTAKE={busy:false};c.PORTAL_PDF={busy:false};c.LIVE_REQUEST={text:'Kaydedilmemiş kendi açıklamam',busy:false,submissionKey:'old'};c.POS.myRole={profile:{name:'Veri Uzmanı'},requirement_version:3,requirements:[requirement()]};c.positionNeedPrefill(9);assert.match(c.LIVE_REQUEST.text,/Kaydedilmemiş kendi açıklamam/);assert.match(c.LIVE_REQUEST.text,/SQL/);assert.equal(c.POS.source.requirement_id,9);assert.equal(c.POS.source.position_version,3);assert.equal(c.LIVE_REQUEST.submissionKey,null);assert.equal(c.state.currentPage,'submitter-request');assert.equal(calls,0);assert.equal(renders,1)});
test('a full existing draft is not truncated by the shortcut',()=>{const c=setup();c.render=c.focusPageStart=()=>{};c.state={};c.INTAKE={busy:false};c.PORTAL_PDF={busy:false};c.LIVE_REQUEST={text:'x'.repeat(4999),busy:false};c.POS.myRole={profile:{name:'Role'},requirement_version:1,requirements:[requirement()]};c.positionNeedPrefill(9);assert.equal(c.LIVE_REQUEST.text,'x'.repeat(4999));assert.match(c.positionSourceBanner(),/SQL/);assert.match(c.positionSourceBanner(),/Henüz talep/)});
test('account change discards role drafts and request source',()=>{const c=setup();c.POS.source={requirement_id:1};c.POS.drafts={1:{name:'Private'}};c.resetPositions();assert.equal(c.POS.source,null);assert.equal(Object.keys(c.POS.drafts).length,0)});
test('out of order position search cannot overwrite current results',async()=>{const c=setup(),nodes={'#positionList':{},'#positionPrev':{},'#positionNext':{}},pending=[];c.$=x=>nodes[x];c.PORTAL={epoch:1};c.portalSkeleton=c.portalEmpty=()=>'';c.apiRequest=()=>new Promise(resolve=>pending.push(resolve));const a=c.loadPositions();c.POS.search='new';const b=c.loadPositions();pending[1]({items:[],total:22,offset:0,limit:20});await b;pending[0]({items:[],total:11,offset:0,limit:20});await a;assert.match(nodes['#positionList'].innerHTML,/22 kayıt/);assert.ok(!nodes['#positionList'].innerHTML.includes('11 kayıt'))});
test('historical request source renders its captured version and escapes authored text',()=>{const c=setup(),html=c.positionRequestSource({position_source:{position_name:'<script>',position_version:1,skill:'SQL',rationale:'<img>',requirement_id:4}});assert.match(html,/sürümü 1/);assert.match(html,/&lt;script&gt;/);assert.ok(!html.includes('<img>'))});
test('successful request retry retains the requirement source of its submission key',async()=>{const c=setup(),source=fs.readFileSync(path.join(__dirname,'../app/static/js/portal.js'),'utf8');vm.runInContext(source.slice(source.indexOf('function bindPortalRequest()'),source.indexOf('function renderListControls(')),c);let submit;const input={value:'Kendi gelişim ihtiyacım',addEventListener(){}},form={addEventListener:(event,callback)=>submit=callback};c.$=key=>key==='#submitterRequestForm'?form:input;c.LIVE_REQUEST={busy:false,text:input.value};c.PORTAL={accountGeneration:1};c.PORTAL_PDF={busy:false};c.POS.source={requirement_id:9};c.state={currentPage:'portal-detail'};c.crypto={randomUUID:()=> 'stable-request-key'};c.renderPortalRequest=c.toast=c.openPortalRequest=()=>{};const sent=[];c.apiRequest=async(url,options)=>{sent.push(JSON.parse(options.body));return {request_id:7}};c.bindPortalRequest();await submit({preventDefault(){}});assert.equal(c.POS.source,null);await submit({preventDefault(){}});assert.equal(sent[0].position_requirement_id,9);assert.equal(sent[1].position_requirement_id,9);assert.equal(sent[0].idempotency_key,sent[1].idempotency_key)});
