const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){const c=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/static/js/skills.js'),'utf8'),c);c.esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');c.portalDateTime=String;return c}
test('published mapping remains read-only and completion carries no proficiency claim',()=>{const c=setup(),html=c.skillCourseSection({id:1,can_edit_skills:false,skills:[{skill:'<Python>',outcome_text:'<script>'}]});assert.ok(!html.includes('data-skill-map-editor'));assert.match(html,/yetkinlik seviyesi doğrulamaz/);assert.match(html,/&lt;Python&gt;/);assert.ok(!html.includes('<script>'))});
test('authorized draft exposes mapping editor using version identifier',()=>{const c=setup(),html=c.skillCourseSection({id:7,can_edit_skills:true,skills:[]});assert.match(html,/data-skill-map-editor="7"/)});
test('analyst sees one confirmation for each unsaved candidate',()=>{const c=setup(),html=c.skillRequestSection({request_id:8,skills:{can_verify:true,items:[],candidates:[{skill_id:2,skill:'Python',labels:['<script>'],analysis_run_id:4}],unmapped_needs:['New topic']}});assert.equal((html.match(/data-skill-confirm-candidate/g)||[]).length,1);assert.ok(!html.includes('checkbox'));assert.match(html,/Henüz doğrulanmadı/);assert.match(html,/Sözlükte eşleşmeyen/);assert.match(html,/&lt;script&gt;/)});
test('employee cannot get analyst controls and duplicate candidate is suppressed',()=>{const c=setup(),data={request_id:8,skills:{can_verify:false,items:[{id:1,skill_id:2,skill:'Python',active:true,human_verified:true,source:'MANUAL'}],candidates:[{skill_id:2,skill:'Python',labels:[]}]}};let html=c.skillRequestSection(data);assert.ok(!html.includes('requestSkillForm'));assert.ok(!html.includes('data-skill-need-action'));data.skills.can_verify=true;html=c.skillRequestSection(data);assert.ok(!html.includes('data-skill-confirm-candidate'));assert.match(html,/WITHDRAW/);assert.match(html,/data-skill-replace/)});
test('historical evidence is labeled and unauthorized evaluation detail has no link',()=>{const c=setup(),html=c.skillEvidenceHTML({id:1,label:'Tamamlandı',observed_at:'2026-09-08',source_current:false,provenance:{meaning:'<script>'},trace:{evaluation_id:9,can_open_evaluation:false,need_request_id:2,course_version_id:3,session_id:4}});assert.match(html,/Geçmiş kayıt/);assert.ok(!html.includes('data-evaluation-open'));assert.match(html,/data-dev-request="2"/);assert.match(html,/data-pub-open="3"/);assert.match(html,/&lt;script&gt;/)});
test('account reset clears skill forms and draft mappings',()=>{const c=setup();c.SKILLS.draft={canonical_name:'Private draft'};c.SKILLS.mapDraft={id:9,rows:[1]};c.SKILLS.options={items:[1]};c.resetSkills();assert.equal(c.SKILLS.draft,null);assert.equal(c.SKILLS.mapDraft,null);assert.equal(c.SKILLS.options,null)});
test('out of order catalog search cannot overwrite the latest response',async()=>{const c=setup(),nodes={'#skillCatalogContent':{},'#skillPrev':{},'#skillNext':{}},pending=[];c.$=x=>nodes[x];c.PORTAL={epoch:1};c.portalSkeleton=()=>'';c.portalEmpty=()=>'';c.portalError=String;c.apiRequest=()=>new Promise(resolve=>pending.push(resolve));const a=c.loadSkillCatalog();c.SKILLS.search='SQL';const b=c.loadSkillCatalog();pending[1]({items:[],total:22,offset:0,limit:20});await b;pending[0]({items:[],total:11,offset:0,limit:20});await a;assert.match(nodes['#skillCatalogContent'].innerHTML,/22 kayıt/);assert.ok(!nodes['#skillCatalogContent'].innerHTML.includes('11 kayıt'))});
test('request verification updates only skill section and preserves decision draft',async()=>{const c=setup(),buttons=[{disabled:false}],section={dataset:{request:'7'},querySelectorAll:()=>buttons,outerHTML:''},decision={value:'Unsent human decision'};c.$=x=>x==='#requestSkills'?section:decision;c.PORTAL={epoch:1};const calls=[];c.apiRequest=async(path,options)=>{calls.push([path,options]);return {can_verify:true,items:[],candidates:[],unmapped_needs:[]}};await c.skillNeedSave(null,{skill_id:2,source:'AI_SUGGESTED',confirm:true});assert.equal(decision.value,'Unsent human decision');assert.equal(calls.length,2);assert.match(section.outerHTML,/requestSkills/);assert.equal(JSON.parse(calls[0][1].body).confirm,true);assert.equal(c.SKILLS.busy,false)});
