const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){const c=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/static/js/training.js'),'utf8'),c);c.esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');return c}
test('training capacity keeps unspecified capacity null and rejects invalid limits',()=>{const c=setup();assert.equal(c.trainingCapacity(''),null);assert.equal(c.trainingCapacity('12'),12);for(const value of ['0','-1','1.2','x'])assert.throws(()=>c.trainingCapacity(value))});
test('session edits cannot change the frozen content version',()=>{const c=setup();c.TRAIN.draft={title:'Ders',responsible_unit:'TECHNICAL_DESIGN',start_at:'',end_at:'',capacity:'',delivery_mode:'ONLINE',online_url:'https://example.com',location:'Hidden old location',expected_version:3};const p=c.trainingFormPayload(false);assert.equal(p.expected_version,3);assert.equal(p.capacity,null);assert.equal(p.location,'');assert.ok(!('course_version_id' in p));assert.equal(p.start_at,null)});
test('training reset clears other account drafts results and delegation',()=>{const c=setup();c.TRAIN.draft={title:'Private'};c.TRAIN.resultDraft={1:{completion:'COMPLETED'}};c.TRAIN.delegationId=4;c.resetTraining();assert.equal(c.TRAIN.draft,null);assert.equal(c.TRAIN.delegationId,null);assert.equal(Object.keys(c.TRAIN.resultDraft).length,0)});
test('catalog plan action is backend-authorized',()=>{const c=setup();assert.equal(c.trainingPlanButton({id:1,can_plan_training:false}),'');assert.match(c.trainingPlanButton({id:1,can_plan_training:true}),/data-training-create="1"/)});
test('request training trace escapes authored data and does not claim request resolution',()=>{const c=setup();const html=c.trainingRequestLinks({training:[{session_id:2,title:'<img src=x>',course_version_number:1,user:{display_name:'<svg>'},attendance:'Katıldı',completion:'Tamamladı',training_completed:true,can_open:true,session_status:'Tamamlandı'}]});assert.ok(!html.includes('<img'));assert.ok(!html.includes('<svg>'));assert.match(html,/İlgili eğitim tamamlandı/);assert.match(html,/kendiliğinden kapatmaz/)});
test('training timezone payload is explicit UTC',()=>{const c=setup();assert.equal(c.trainingUTC('2026-10-01T09:00:00+03:00'),'2026-10-01T06:00:00.000Z');assert.equal(c.trainingUTC(''),null);assert.throws(()=>c.trainingUTC('bad-date'))});
test('out of order training queue results cannot replace the newest filter',async()=>{const c=setup(),nodes={'#trainingQueue':{},'#trainingPrev':{},'#trainingNext':{}},pending=[];c.$=x=>nodes[x];c.PORTAL={epoch:1};c.portalSkeleton=()=>'';c.portalEmpty=(a)=>a;c.portalError=String;c.apiRequest=()=>new Promise(resolve=>pending.push(resolve));const first=c.loadTrainingQueue();c.TRAIN.status='COMPLETED';const second=c.loadTrainingQueue();pending[1]({items:[],total:22,offset:0,limit:20});await second;pending[0]({items:[],total:11,offset:0,limit:20});await first;assert.match(nodes['#trainingQueue'].innerHTML,/22 oturum/);assert.ok(!nodes['#trainingQueue'].innerHTML.includes('11 oturum'))});
